### ISSUE TITLE
Discrepancy in Reproduced Results for LLaMA2 on "qmsum" and "qasper" tasks.

### ISSUE THREAD

**Issue by ilur98** [jy-yuan/KIVI#7]
This is a nice work! When I try to benchmark the Llama2-7b with KIVI (Llama-2-7b-hf_4096_4bits_group32_residual128). I found that the tasks "qmsum" and "qasper" are much lower than the results in the paper. I also found that the sequence length of these two tasks is much longer than 4096. For example, the average length of "qmsum" is about 10k.  This may be the reason the performance on two tasks are so poor. So what should I do to obtain the result in the paper? 
What follows are the results I get.
{
    "samsum": 41.59,
    "multi_news": 1.32,
    **"qmsum": 7.07,**
    "repobench-p": 59.97,
    "trec": 66.0,
    "triviaqa": 87.72,
    **"qasper": 5.96,**
    "lcc": 66.76
}

**Comment by zirui-ray-liu** [comment]
Thank you for your interests! Are you using our [longbench evaluation protocol](https://github.com/jy-yuan/KIVI/blob/main/pred_long_bench.py)? We follow the implementation of the [Longbench official repo](https://github.com/THUDM/LongBench/blob/main/pred.py#L60). For Llama-2-7b, its context length is 4k. Because LLMs perform poorly when serving length > pretrained length, so for prompts with >4k length, it will truncate the prompt with only the first 2K tokens and the last 2K tokens.

Let me know if you still cannot reproduce the results.

**Comment by ilur98** [comment]
Thank you for solving my confusion.
